import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeroHeader } from "./Components/navbar";
import WhatsAppButton from "./Components/WhatsAppButton";
import AnnouncementBarStacked from "./Components/AnnouncementBarStacked";
import FooterGlow from "./Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SH BridalMakeover",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <AnnouncementBarStacked />
        <div className="pt-7">
          <HeroHeader />
        </div>
        {children}
        <WhatsAppButton />
        <FooterGlow />
      </body>
    </html>
  );
}
