import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import "./globals.css";
import { HeroHeader } from "./Components/navbar";
import WhatsAppButton from "./Components/WhatsAppButton";
import AnnouncementBarStacked from "./Components/AnnouncementBarStacked";
import FooterGlow from "./Components/Footer";

const outfit = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "SH BridalMakeover",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${outfit.className}  antialiased bg-black`}>
        <AnnouncementBarStacked />

        <HeroHeader />

        {children}
        <WhatsAppButton />
        <FooterGlow />
      </body>
    </html>
  );
}
